property:
  gpu-id: {{gpu_id}}
  gie-unique-id: {{gie_unique_id}}
  batch-size: {{batch_size}}

  onnx-file: "{{MODEL_REPO_ROOT_DIR}}/{{MODEL_NAME}}/{{MODEL_VERSION}}/model.onnx"
  model-engine-file: "{{MODEL_REPO_ROOT_DIR}}/{{MODEL_NAME}}/{{MODEL_VERSION}}/model.onnx_b{{batch_size}}_gpu{{gpu_id}}_{{network_mode_name}}.engine"

  # 0=FP32, 1=INT8, 2=FP16 (khớp với engine .plan)
  network-mode: {{network_mode}}
  # interval: {{interval}}
  network-type: {{network_type}} # 1 = Classifier, 2 = Detector, 3 = Segmenter

  # === Preprocess (tương đương preprocess trong infer_config cũ) ===
  net-scale-factor: {{net_scale_factor}}
  model-color-format: {{model_color_format}} # 0=RGB 1=BGR
  maintain-aspect-ratio: {{maintain_aspect_ratio}}
  symmetric-padding: {{symmetric_padding}}

  # === Labels / classes ===
  labelfile-path: "{{COMPONENT_ROOT_DIR}}/labels.txt"

  # === Classifier behavior ===
  classifier-threshold: {{classifier_threshold}}
  classifier-async-mode: 1 # tương đương input_control.async_mode (secondary only) :contentReference[oaicite:5]{index=5}
  classifier-type: "person_attr"

  # === Parser YOLO custom ===
  custom-lib-path: "{{WORKSPACE_PATH}}/plugins/liblantana_person_attr_24label.so"
  parse-classifier-func-name: "NvDsInferClassifierParseCustomPersonAttr24Label"

  # =========================
  # Secondary / operate-on-* (nếu dùng làm SGIE, bỏ comment)
  # =========================
  # process-mode=2                 # 1=Primary (full-frame), 2=Secondary (objects)
  # operate-on-gie-id={{OPERATE_ON_PGIE_ID}}
  # operate-on-class-ids={{OPERATE_ON_CLASS_IDS}}
  # secondary-reinfer-interval=3
  
