processing:
  elements:
    - id: pgie_detection
      type: nvinfer # nvinfer (TensorRT) | nvinferserver (Triton)
      role: primary_inference
      unique_id: 1 # gie-unique-id — identifies metadata downstream
      config_file: "/opt/vms_engine/dev/pipeline_components/pgie_phat-hien-khuon-mat_DETECTION/package_content/config_infer_engine_placeholder.yml"
      process_mode: 1 # 1=Primary (full-frame) | 2=Secondary (per-object)
      # interval: 3 # skip N batches between inferences (0 = every frame)
      # batch_size: 4 # must equal sources.max_batch_size
      gpu_id: 0
      queue: {} # → queue before pgie (use defaults)

    - id: tracker
      type: nvtracker
      ll_lib_file: "/opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so"
      ll_config_file: "/opt/vms_engine/build/bin/configs/config_tracker_NvDCF_perf.yml"
      tracker_width: 640 # frame is scaled to this width before tracking
      tracker_height: 640
      gpu_id: 0
      compute_hw: 1 # 0=default  1=GPU  2=VIC (Jetson only)
      user_meta_pool_size: 512 # buffer pool for misc tracker output (Re-ID, past-frame, etc.)
      queue: {} # → queue before tracker


    # - id: demuxer
    #   type: nvstreamdemux
    #   queue: {}                 # → queue before demuxer
