property:
  gpu-id: 0
  # gie-unique-id: 1
  batch-size: 8

  onnx-file: "{{MODEL_REPO_ROOT_DIR}}/{{MODEL_NAME}}/{{MODEL_VERSION}}/model.onnx"
  model-engine-file: "{{MODEL_REPO_ROOT_DIR}}/{{MODEL_NAME}}/{{MODEL_VERSION}}/model.plan"

  # 0=FP32, 1=INT8, 2=FP16 (khớp với engine .plan)
  network-mode: 0
  # interval: 3
  network-type: 1 # 1 = Classifier, 2 = Detector, 3 = Segmenter
  # === Preprocess (tương đương preprocess trong infer_config cũ) ===
  infer-dims: "3;64;128"
  network-input-order: 1 # 0=NCHW, 1=NHWC
  output-blob-names: "Identity:0"
  net-scale-factor: 1
  model-color-format: 0 # 0=RGB 1=BGR
  maintain-aspect-ratio: 0

  # === Labels / classes ===
  labelfile-path: "{{COMPONENT_ROOT_DIR}}/labels.txt"

  # === Classifier behavior ===
  classifier-threshold: 0.51
  classifier-async-mode: 0 # tương đương input_control.async_mode (secondary only)
  classifier-type: "lprecg_ocr"

  # === Parser YOLO custom ===
  custom-lib-path: "{{WORKSPACE_PATH}}/plugins/libocr_fast_plate_parser.so"
  parse-classifier-func-name: "NvDsInferClassifierParseCustomFastPlateOCR"

  # =========================
  # Secondary / operate-on-* (nếu dùng làm SGIE, bỏ comment)
  # =========================
  # process-mode=2                 # 1=Primary (full-frame), 2=Secondary (objects)
  # operate-on-gie-id={{OPERATE_ON_PGIE_ID}}
  # operate-on-class-ids={{OPERATE_ON_CLASS_IDS}}
  # secondary-reinfer-interval=3
